int _abs(int);
int add(int, int);
int _isalpha(int c);
int _islower(int c);
int print_last_digit(int);
int print_sign(int n);
int _putchar(char c);
void jack_bauer(void);
void print_alphabet(void);
void print_alphabet_x10(void);
void print_times_table(int n);
void print_to_98(int n);
void times_table(void);
